### ISSUE TITLE
OSC script broken - Font issue?

### ISSUE THREAD

**Issue by Xathros1** [cyl0/ModernX#32]
Hi, it seems that somehow the osc script broke along the way, affected host os are MacOS and Linux afaik 
https://github.com/Tsubajashi/mpv-settings/issues/19

The error looks like this on affected systems:

MacOS 
 ![mpv](https://user-images.githubusercontent.com/1530401/203523979-03de48ee-3a63-4bf0-b7b0-70e0975554a2.png)

Linux (Opensuse Tumbleweed)
![Bildschirmfoto vom 2022-11-23 12-55-54](https://user-images.githubusercontent.com/72621668/203540899-e027aa96-9b8e-483c-86c8-1d303fba5b35.png)

Any idea what's causing this?

**Comment by po5** [comment]
Follow the install instructions. Works on linux.

**Comment by Larnee** [comment]
I'm having the exact same problem on Fedora 37.
