### ISSUE TITLE
Default font size for titles

### ISSUE THREAD

**Issue by Keith94** [cyl0/ModernX#34]
If you have a really long title, it gets cut off kind of abruptly at the end. Is there a way we can reduce the default font size to mitigate the issue?

Or other solutions to display them.. i.e. Add "..." ellipses at the end, or a fade effect (i.e. browser tab titles), or dynamically reduce the font size so the full title fits the screen. Maybe even horizontally scrolling text if that's not too hard to implement.

![image](https://user-images.githubusercontent.com/5490615/204106456-13ea9ff9-a293-48f1-9677-13b5714b4e96.png)

**Comment by Keith94** [comment]
Fixed by [9ba012b](https://github.com/cyl0/ModernX/commit/9ba012bef0b4882c0e3a92c56d2a4788656f9adc)

**Comment by Enivex** [comment]
> Fixed by [9ba012b](https://github.com/cyl0/ModernX/commit/9ba012bef0b4882c0e3a92c56d2a4788656f9adc)

My titles are now cut off by ellipses only halfway through my window. I had to change the 23 to a smaller number.

**Comment by Keith94** [comment]
Good point. I hope someone could address that.

**Comment by Enivex** [comment]
I realized that the font size can be adjusted by changing the number after on line 158 in the lua file

    Title = '{\\blur1\\bord0.5\\1c&HFFFFFF&\\3c&H0\\fs24\\q2\\fn' .. user_opts.font .. '}',

The original number was 38

(Not exactly user friendly though)

**Comment by zydezu** [comment]
> Good point. I hope someone could address that.

go to `lo.button.maxchars = geo.w / 23` (line 1349) and change '23' to a lower value like '14'... the '...' cutoff will be closer to the edge of the screen.

**Comment by zydezu** [comment]
![mpv_JHhzyoowr7](https://user-images.githubusercontent.com/50119098/232329849-4cd07d7e-5027-40b5-80b3-c42d279d8e74.gif)

Here is a script with those changed and the ability for text scrolling applied:
[modernx.zip](https://github.com/cyl0/ModernX/files/11242976/modernx.zip)

I've also added the changes to my own fork of ModernX :
https://github.com/zydezu/ModernX

**Comment by Keith94** [comment]
@zydezu Why was the titlecutoff removed in the latest version? Any way to get it back?

**Comment by zydezu** [comment]
Some code about titles was changed and it caused it to be buggy with CJK characters. An alternative as of now is clicking the title will show a OSD message in the top left of the screen with the title (and right clicking the file name). 

If I can get it working properly, scrolling may return in a future update.

**Comment by Keith94** [comment]
Ok i see. Will watch for updates

vidscale=yes is another possible workaround, it also fixes the windowtitle overflowing because it does not have ellipses either :(

**Comment by zydezu** [comment]
> Ok i see. Will watch for updates
> 
> vidscale=yes is another possible workaround, it also fixes the windowtitle overflowing because it does not have ellipses either :(

So far I've fixed the window title's cutting off (or not) at wrong places.

![mpv_LZVMPNyQki](https://github.com/cyl0/ModernX/assets/50119098/c0523a57-aba7-40e0-a1c3-cfdb5241a25f)

**Comment by Keith94** [comment]
Wow great job! It's working perfectly on my end now. :)

I actually prefer that to the scrolling behavior, which can be a little distracting at times

**Comment by Keith94** [comment]
Closing in favor of @zydezu's fork 👍
