### ISSUE TITLE
I don't see the thumbnail scripts working

### ISSUE THREAD

**Issue by daddycool322** [cyl0/ModernX#44]
Hey, I'm using MPV with https://github.com/cyl0/ModernX. But thumbnail seems not working I don't know why

**Comment by RepathZT** [comment]
either don't use the `0.5.0` release version (use the one in the main branch) or use the [thumbnailer-dev](https://github.com/cyl0/ModernX/tree/thumbnailer-dev) branch

**Comment by po5** [comment]
The `thumbnailer-dev` branch is the old implementation. Just use the main branch.

**Comment by cyl0** [comment]
The latest `0.6.0` release should now have thumnailer support.
