### ISSUE TITLE
Volume slider scaling value incorrect

### ISSUE THREAD

**Issue by RepathZT** [cyl0/ModernX#45]
https://github.com/cyl0/ModernX/blob/ccb54f7c754969630426fb1798952023f11a06e6/modernx.lua#L1777

should be `val+val` for proper volume slider scaling

**Comment by cyl0** [comment]
The volume slider not scaling linear seems to be intended behaviour, as this was how it was implemented in the upstream modern, I'm guessing it has to with trying to be more in line with perceptual loudness. If enough people find this to be an issue, then maybe we can get an alternative linear scaling implemented.
