### ISSUE TITLE
Change thumbnail border size and show milliseconds

### ISSUE THREAD

**Issue by Keith94** [cyl0/ModernX#46]
https://github.com/maoiscat/mpv-osc-modern/pull/34
https://github.com/maoiscat/mpv-osc-modern/pull/33

A couple new features were added in the original  branch; hope we can see them here.

EDIT:

Also
https://github.com/maoiscat/mpv-osc-modern/pull/40
https://github.com/maoiscat/mpv-osc-modern/pull/41

**Comment by zydezu** [comment]
ive added these to my fork : https://github.com/zydezu/modernX

**Comment by Keith94** [comment]
Works great! Thank you

**Comment by Keith94** [comment]
Can you tell me how to get the jump 5s button back in your fork? Seems to have disappeared even with default settings

**Comment by zydezu** [comment]
> Can you tell me how to get the jump 5s button back in your fork? Seems to have disappeared even with default settings

in the configuration ( osc.conf or the modernX.lua code itself ) , disable ‘compactmode’

**Comment by Keith94** [comment]
> > Can you tell me how to get the jump 5s button back in your fork? Seems to have disappeared even with default settings
> 
> in the configuration ( osc.conf or the modernX.lua code itself ) , disable ‘compactmode’

Thanks again for the help man

**Comment by Keith94** [comment]
Closing in favor of @zydezu's fork 👍
