### ISSUE TITLE
How do you convert the icons in the file

### ISSUE THREAD

**Issue by Qiyue0726** [cyl0/ModernX#47]
The file opens with something like `play = '\239\142\170'`, I opened the file using vs code, how do I know its original icon?

**Comment by dexeonify** [comment]
Find the icons in https://zavoloklom.github.io/material-design-iconic-font/icons.html. For example, the `zmdi-skip-next` icon. Copy the icon (yes, literally the icon) like: . Don't worry if it doesn't display for you. Then use a website like https://onlineunicodetools.com/convert-unicode-to-decimal to convert the icon to decimal. Make sure there is no space after your icon.

The result should be 3 groups of numbers with 3 numbers each, like so: `239 142 180`. You then add slashes in between the spaces `\239\142\180` to be understood by mpv.

**Comment by Qiyue0726** [comment]
Thank you, I get it
