### ISSUE TITLE
[Feature request] Please add a repeat forever icon  

### ISSUE THREAD

**Issue by blueray453** [cyl0/ModernX#52]
Please add a button for repeat forever like https://github.com/longtermfree/oscc

**Comment by zydezu** [comment]
That feature is in this fork : https://github.com/zydezu/ModernX

**Comment by blueray453** [comment]
@zydezu I have made a osc.conf file in script-opts and put the following lines there.

```
showinfo=false
showjump=false
```
But it seems to have no effect. Only changing the `user_opts` in `modernx.lua` works. Do you have any idea why is that?

**Comment by kimagurefr** [comment]
@blueray453 in mpv configuration files (including osc.conf), you must use yes/no for boolean values, not true/false.
Can you try with 
```
showinfo=no
showjump=no

```

**Comment by blueray453** [comment]
Did you notice that the fork does not remember the state of the "loop button". I mean if we enable loop then after the restart, the system should remember that i want to loop the video.

Currently I use the following code to remember volume state (sorry, forget from which gist i copy pasted it from).

```
local filepath = mp.command_native({"expand-path", "~~/volume"})

local loadfile = io.open(filepath, "r")

if loadfile then
	set_volume = string.sub(loadfile:read(), 8)
	loadfile:close()
	mp.set_property_number("volume", set_volume)
end

mp.register_event("shutdown", 
	function()
		local savefile  = io.open(filepath, "w+")
		savefile:write("volume=" .. mp.get_property("volume"), "\n")    
		savefile:close()
	end
)
```
How can I make the loop state persistent.

**Comment by Keith94** [comment]
Its not persistent for me either sadly. Toggle would be nice

**Comment by zydezu** [comment]
should i add this feature to the fork, when i added a "loop" button, I was think it'd be a temporary thing- but I can add this as an optional feature if wanted (although maybe it'd be better in a seperate .lua file as this status saving in not something modernX concerns).

> @Keith94
> 
> > Its not persistent for me either sadly. Toggle would be nice
> 
> Alhamdulillah, the issue is solved for me:
> 
> For loop button, the lua file is:
> 
> ```
> local filepath = mp.command_native({"expand-path", "~~/loop-file-states"})
> 
> local loadfile = io.open(filepath, "r")
> 
> if loadfile then
>     set_loop_file = string.sub(loadfile:read(), 11)
>     loadfile:close()
>     mp.set_property("loop-file", set_loop_file)
> end
> 
> mp.register_event("shutdown",
>     function()
>         local savefile  = io.open(filepath, "w+")
>         savefile:write("loop-file=" .. mp.get_property("loop-file"), "\n")
>         savefile:close()
>     end
> )
> ```
> 
> For volume, the lua file is:
> 
> ```
> local filepath = mp.command_native({"expand-path", "~~/volume-state"})
> 
> local loadfile = io.open(filepath, "r")
> 
> if loadfile then
> 	set_volume = string.sub(loadfile:read(), 8)
> 	loadfile:close()
> 	mp.set_property("volume", set_volume)
> end
> 
> mp.register_event("shutdown",
> 	function()
> 		local savefile  = io.open(filepath, "w+")
> 		savefile:write("volume=" .. mp.get_property("volume"), "\n")
> 		savefile:close()
> 	end
> )
> ```
> 
> For subtitle, the lua file is:
> 
> ```
> local filepath = mp.command_native({"expand-path", "~~/subtitle-state"})
> 
> local loadfile = io.open(filepath, "r")
> 
> if loadfile then
> 	set_sid = string.sub(loadfile:read(), 5)
> 	loadfile:close()
> 	mp.set_property("sid", set_sid)
> end
> 
> mp.register_event("shutdown",
> 	function()
> 		local savefile  = io.open(filepath, "w+")
> 		savefile:write("sid=" .. mp.get_property("sid"), "\n")
> 		savefile:close()
> 	end
> )
> ```

should i add this feature to the fork, when i added a "loop" button, I was think it'd be a temporary thing- but I can add this as an optional feature if wanted (although maybe it'd be better in a seperate .lua file as this status saving in not something modernX concerns).

**Comment by blueray453** [comment]
@zydezu please add this to the fork. It will be helpful for us.

**Comment by zydezu** [comment]
> 

ok ill look into it~
also by the way using `save-position-on-quit=yes` will save the subtitle and volume (and position) states of a video.
