### ISSUE TITLE
Why Volume Control Is Greyed Out When Playing MP3

### ISSUE THREAD

**Issue by blueray453** [cyl0/ModernX#53]
Here is a screenshot.

![test](https://user-images.githubusercontent.com/855297/232991493-f45bb740-d01b-4190-be87-c9c2eb4560ed.png)

As you can see I can not change the volume when playing mp3 files. What might be the reason?

**Comment by blueray453** [comment]
I want to mention that up and down arrow works for increase and decrease volume for mp3 (just can not use the volume control in the OSC).

**Comment by blueray453** [comment]
I forgot to add some context to this issue.

When I was playing mp3 in mpv, there was no gui. So, i added https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua and got a gui. More about this on https://github.com/mpv-player/mpv/issues/6025#issuecomment-1493346580. 

So, the three players in this issue are 

https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua
https://github.com/cyl0/ModernX
https://github.com/mpv-player/mpv

So, actually not sure who can fix this problem.

**Comment by medicamin** [comment]
I confirm this issue not only happens when visualizer.lua script is enabled, but even I enable visualizer in the commandline by something like this:
```
--lavfi-complex="[aid1]asplit[ao][a]; [a]showcqt[vo]"
```
