### ISSUE TITLE
OSC only appears when hovering

### ISSUE THREAD

**Issue by Keith94** [cyl0/ModernX#57]
@zydezu

In your fork, the osc doesn't show up with small mouse movements, it only shows up when hovering over the osc or title bar area. Can you confirm that its broken and how to fix? I tried minmousemove=0 but it didn't seem to work. 0 is the default value with stock osc: https://[mpv.io](https://mpv.io/manual/master/#on-screen-controller-minmousemove)/manual/master/#on-screen-controller-minmousemove

**Comment by zydezu** [comment]
this option is under `bottomhover`, setting it to false will enable the old behaviour. ( See [https://github.com/zydezu/modernX ](https://github.com/zydezu/modernX ))

**Comment by Keith94** [comment]
OK perfect. I added bottomhover=no to modernx.conf and that did the trick. I feel dumb for missing that. Thanks!!
