### ISSUE TITLE
Upsizing the timestamps without scaling the entire UI

### ISSUE THREAD

**Issue by manan-gup** [cyl0/ModernX#58]
Hi,

I'm very happy with the size of the UI but the timestamps are too small for me. Is there any way to change the font size for the timestamps without scaling the entire UI?

If not then can such an option be added (or point me to the right variables as I can't seem to figure out where to set the size)?

P.S. Thanks for the excellent script!

**Comment by zydezu** [comment]
Line 156: `Time = '{\\blur0\\bord0\\1c&HFFFFFF&\\3c&H000000&\\fs17\\fn' .. user_opts.font .. '}',`  change the number `17` - that is the font size...

perhaps an option could be added, but the maintainer of the repos seems absent.

**Comment by zydezu** [comment]
I've added the option to my fork : https://github.com/zydezu/mpvconfig

**Comment by manan-gup** [comment]
Thanks a lot. Worked as expected. Closing.
