### ISSUE TITLE
Problem with thumbfast?

### ISSUE THREAD

**Issue by vhagedorn** [cyl0/ModernX#63]
I am experiencing a problem on Mac OS Ventura. When I play any video via `open` or double-click in Finder, it opens a new mpv instance. If I then hover over the timeline (and generate thumbnails, invoking thumbfast I suspect), the mpv icon will sort of stutter in the dock and then gets stuck there. 

When I say "stuck", I mean that it works until I finish the video or quit, but then it stays open and won't quit unless I `pkill` or Force Quit. The funny thing is it works fine and as expected if I run via `mpv`, just not through `open` or Finder. I am perplexed as to why this is happening... it seems to just sort of bug out when invoking thumbfast.

Here is a video of the issue: [https://imgur.com/a/itxg5AP](https://imgur.com/a/itxg5AP)

I'm not sure if this is an issue with thumbfast or not, but I only have ModernX and and thumbfast installed and when I remove either of them this issue goes away.

Hopefully someone can help me resolve this annoying issue, but either way: thank you for reading.

**Comment by po5** [comment]
Wrong issue tracker, and please read the thumbfast README.

**Comment by vhagedorn** [comment]
So I completely uninstalled mpv and then reinstalled mpv via homebrew (I guess I was using the formula instead of the cask? idk). It still does the jumping thing, but now it quits like normal so I'm gonna go ahead and close this.

Moral of the story: when facing any kind of issue on OS X check for mixed installs or just reinstall entirely.

Thanks for pointing me in the right direction!

**Comment by po5** [comment]
Check console output or thumbfast README for instructions on how to create a symlink that gets rid of the jumping dock icon.
