### ISSUE TITLE
mpv showing "The shared-script-properties property is deprecated and will be removed in the future. Use the user-data property instead." warning

### ISSUE THREAD

**Issue by fighuass** [cyl0/ModernX#64]
Currently running mpv 0.37.0, and I'm getting a "The shared-script-properties property is deprecated and will be removed in the future. Use the user-data property instead." warning if I use ModernX.

Heads up for the dev?

**Comment by zydezu** [comment]
This repo seems dead — but this issue came up here : https://github.com/zydezu/mpvconfig/issues/6

**Comment by cyl0** [comment]
should be fixed by 726e71ffa46d4ad05d4a9dfba7c48f1c68ef3ada
