### ISSUE TITLE
The video description of online videos does not support Chinese, which displays garbled characters

### ISSUE THREAD

**Issue by ywq0056** [cyl0/ModernX#66]
<img width="640" alt="1" src="https://github.com/cyl0/ModernX/assets/142240860/9507c2c1-9f3c-49ed-aad9-52aa7e72cc7f">

As shown in the figure, the Chinese language involved in watching online videos cannot be displayed properly. I am not sure if it is possible to add support for Chinese language. Thank you very much

**Comment by zydezu** [comment]
This concerns >> https://github.com/zydezu/mpvconfig/issues/12
