### ISSUE TITLE
Showing the full title on the OSC

### ISSUE THREAD

**Issue by Sharad104** [cyl0/ModernX#68]
![Screenshot_1](https://github.com/cyl0/ModernX/assets/85397332/145b5a7b-f897-45ce-9025-80a878332552)
showing the full title : [Hi10][Dual-Audio]

how to make it show the full title ,lots of space is left but script somehow isn't using it for display.

**Comment by SharadJ19** [comment]
line no.1353 :
replaced
`lo.button.maxchars = geo.w / 23`
                       with
`lo.button.maxchars = geo.w / 16`
Working as intended !   
got info from 
https://github.com/maoiscat/mpv-osc-modern/issues/49#issuecomment-1987101205
